env:
  commonjs: true
  es6: true
  node: true
  jest: true
extends: ['eslint:recommended']
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-console: ["error"]
  operator-linebreak: ["error", "before"]
  padding-line-between-statements:
    - "error"
    - blankLine: "always"
      prev: "*"
      next: "return"
  func-style: ["error", "declaration"]
  require-await: "error"
  quotes: ["error", "single"]
  semi: ["error", "always"]
  no-var: "error"
  prefer-const:
    - "error"
    - destructuring: "all"
  max-len:
    - "error"
    - code: 80
  